1

diff --git a/.github/workflows/main9.yml b/.github/workflows/main9.yml
--- a/.github/workflows/main9.yml
+++ b/.github/workflows/main9.yml
@@ -7,7 +7,7 @@ env:
   PROFILE_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/profile:${{ github.sha }}
   ACCOUNT_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/account:${{ github.sha }}
   FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
-  ROLLOUTS: './.k8s/charts/templates/rollouts.yaml'
+
 
 jobs:
 
@@ -110,13 +110,13 @@ jobs:
 
       - name: Install Yandex Cloud CLI non-interactively
         run: |
-          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i $HOME/.yandex-cloud -n
-          echo "$HOME/.yandex-cloud/bin" >> $GITHUB_PATH
+            curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i $HOME/.yandex-cloud -n
+            echo "$HOME/.yandex-cloud/bin" >> $GITHUB_PATH
 
       - name: Save Kubeconfig to File
         run: |
-          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yml
-          chmod 600 kubeconfig.yml
+            echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yml
+            chmod 600 kubeconfig.yml
 
       - name: Install Argo Rollouts CLI
         run: |
@@ -128,13 +128,9 @@ jobs:
 
       - name: Deploy to Kubernetes
         run: |
-            #rollouts=("account-rollout" "profile-rollout" ") # Замените имена на актуальные
-            #for rollout in "${rollouts[@]}"
-          
             DATE=$(date +%Y%m%d-%H%M)
             COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
             RELEASE_NAME=myapp-${DATE}-${COMMIT_SHA}
-          
           
             # Обновление Helm чартов с новым образом
             helm upgrade --install $RELEASE_NAME ./.k8s/charts/ --set account.image.tag=${{ github.sha }},profile.image.tag=${{ github.sha }} --namespace default --create-namespace --kubeconfig=kubeconfig.yml
@@ -146,19 +142,19 @@ jobs:
       #Проверка здоровья развертывания
       - name: Check health of new application versions
         run: |
-          # Ожидание, пока развертывание не станет здоровым
-          kubectl argo rollouts -n default wait rollout profile-rollout --for condition=Healthy --kubeconfig=kubeconfig.yml
-          kubectl argo rollouts -n default wait rollout account-rollout --for condition=Healthy --kubeconfig=kubeconfig.yml
-          # Здесь можно добавить дополнительные тесты для проверки работоспособности приложения
-          # Пример проверки доступности HTTP эндпоинта
-          # curl --fail http://myapp.example.com/health || exit 1
+            # Ожидание, пока развертывание не станет здоровым
+            kubectl argo rollouts -n default wait rollout profile-rollout --for condition=Healthy --kubeconfig=kubeconfig.yml
+            kubectl argo rollouts -n default wait rollout account-rollout --for condition=Healthy --kubeconfig=kubeconfig.yml
+            # Здесь можно добавить дополнительные тесты для проверки работоспособности приложения
+            # Пример проверки доступности HTTP эндпоинта
+            # curl --fail http://myapp.example.com/health || exit 1
 
       #Продвижение развертывания
       - name: Promote Rollout
         run: |
-          # Промоушн новой версии после успешной проверки
-          kubectl argo rollouts -n default promote profile-rollout --kubeconfig=kubeconfig.yml
-          kubectl argo rollouts -n default promote account-rollout --kubeconfig=kubeconfig.yml
+            # Промоушн новой версии после успешной проверки
+            kubectl argo rollouts -n default promote profile-rollout --kubeconfig=kubeconfig.yml
+            kubectl argo rollouts -n default promote account-rollout --kubeconfig=kubeconfig.yml
      
       
       
