1

diff --git a/.github/workflows/main9.yml b/.github/workflows/main9.yml
--- a/.github/workflows/main9.yml
+++ b/.github/workflows/main9.yml
@@ -182,18 +182,18 @@ jobs:
           RELEASE_NAME_NEXT="release-ingress-$NEXT_VERSION"
 
           # Проверяем существование Ingress следующей версии
-          if ! kubectl get ingress $RELEASE_NAME_NEXT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
+          #if ! kubectl get ingress $RELEASE_NAME_NEXT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
             # Если Ingress следующей версии не существует, проверяем существование текущей версии
-            if ! kubectl get ingress $RELEASE_NAME_CURRENT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
-                  echo "Ingress for current and next versions does not exist. Installing $RELEASE_NAME_NEXT..."
+          #  if ! kubectl get ingress $RELEASE_NAME_CURRENT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
+          #        echo "Ingress for current and next versions does not exist. Installing $RELEASE_NAME_NEXT..."
                   helm install $RELEASE_NAME_NEXT ./.k8s/ingress --namespace default --kubeconfig=kubeconfig.yml --set global.activeVersion=$NEXT_VERSION --debug
-            else
-                  echo "Upgrading $RELEASE_NAME_CURRENT to $RELEASE_NAME_NEXT..."
-                  helm upgrade --install $RELEASE_NAME_NEXT ./.k8s/ingress --namespace default --kubeconfig=kubeconfig.yml --set global.activeVersion=$NEXT_VERSION --debug
-            fi
-          else
-            echo "Ingress $RELEASE_NAME_NEXT already exists, no action required."
-          fi
+          #  else
+          #        echo "Upgrading $RELEASE_NAME_CURRENT to $RELEASE_NAME_NEXT..."
+          #        helm upgrade --install $RELEASE_NAME_NEXT ./.k8s/ingress --namespace default --kubeconfig=kubeconfig.yml --set global.activeVersion=$NEXT_VERSION --debug
+          #  fi
+          #else
+          #  echo "Ingress $RELEASE_NAME_NEXT already exists, no action required."
+          #fi
 
 
 
