1

diff --git a/.github/workflows/main9.yml b/.github/workflows/main9.yml
--- a/.github/workflows/main9.yml
+++ b/.github/workflows/main9.yml
@@ -183,18 +183,20 @@ jobs:
           RELEASE_NAME_NEXT="ingress-$NEXT_VERSION"
 
           # Проверяем существование Ingress следующей версии
-          if helm get manifest $RELEASE_NAME_NEXT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
-             echo "Ingress $RELEASE_NAME_NEXT already exists, no action required."
+          if ! kubectl get ingress $RELEASE_NAME_NEXT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
+            # Если Ingress следующей версии не существует, проверяем существование текущей версии
+            if ! kubectl get ingress $RELEASE_NAME_CURRENT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
+                  echo "Ingress for current and next versions does not exist. Installing $RELEASE_NAME_NEXT..."
+                  helm install $RELEASE_NAME_NEXT ./.k8s/ingress --namespace default --kubeconfig=kubeconfig.yml --debug
+            else
+                  echo "Upgrading $RELEASE_NAME_CURRENT to $RELEASE_NAME_NEXT..."
+                  helm upgrade --install $RELEASE_NAME_NEXT ./.k8s/ingress --namespace default --kubeconfig=kubeconfig.yml --debug
+            fi
           else
-             # Если Ingress следующей версии не существует, проверяем существование текущей версии
-             if helm get manifest $RELEASE_NAME_CURRENT -n default --kubeconfig=kubeconfig.yml > /dev/null 2>&1; then
-                 echo "Upgrading $RELEASE_NAME_CURRENT to $RELEASE_NAME_NEXT..."
-                 helm upgrade --install $RELEASE_NAME_NEXT ./.k8s/ingress --namespace default --kubeconfig=kubeconfig.yml --debug
-             else
-               echo "Ingress for current and next versions does not exist. Installing $RELEASE_NAME_NEXT..."
-               helm install $RELEASE_NAME_NEXT ./.k8s/ingress --namespace default --kubeconfig=kubeconfig.yml --debug
-             fi
+            echo "Ingress $RELEASE_NAME_NEXT already exists, no action required."
           fi
+
+
 
       
       
